import os
import re
import subprocess
from pathlib import Path

def get_gemini_summary(url):
    """
    Fetches content from a URL, and uses Gemini to generate a summary.
    """
    try:
        # Check if gemini is installed
        subprocess.run(['gemini', '--version'], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("Gemini CLI not found. Please install it to generate summaries.")
        return None

    try:
        # Fetch HTML, extract readable text, and then pass to Gemini for summary
        # Using a pipe to connect the commands
        w3m_process = subprocess.Popen(['w3m', '-T', 'text/html', '-dump', url], stdout=subprocess.PIPE)
        gemini_process = subprocess.Popen(['gemini', 'summarize', '-'], stdin=w3m_process.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Allow w3m_process to receive a SIGPIPE if gemini_process exits.
        w3m_process.stdout.close()
        
        summary_bytes, error_bytes = gemini_process.communicate()

        if gemini_process.returncode != 0:
            print(f"Gemini process failed for {url}: {error_bytes.decode('utf-8')}")
            return None

        summary = summary_bytes.decode('utf-8').strip()
        # Clean the summary
        return summary.replace('"', '').replace("'", "")

    except Exception as e:
        print(f"Error generating summary for {url}: {e}")
        return None


def add_descriptions_and_alt_text_to_posts(posts_dir):
    """
    Adds a 'description' and 'image_alt' field to the front matter of Markdown posts if they are missing.
    The description is generated by fetching the content from the post's URL and summarizing it.
    The image_alt is generated from the title if not present.
    """
    for filepath in Path(posts_dir).rglob('*.md'):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()

            parts = content.split('---', 2)
            if len(parts) < 3:
                print(f"Skipping {filepath}: Not a valid front matter format.")
                continue

            front_matter_str = parts[1]
            body = parts[2].strip()
            
            # Check if description needs to be updated or added
            # We'll update if it's missing or a placeholder.
            update_description = 'description:' not in front_matter_str or 'description: ""' in front_matter_str or len(re.search(r'description:\s*"(.*?)"', front_matter_str).group(1)) < 50
            
            new_front_matter_str = front_matter_str.strip()
            made_changes = False

            if update_description:
                url_match = re.search(r'\[Read the full article here\]\((.*?)\)', body)
                if url_match:
                    url = url_match.group(1)
                    print(f"Generating summary for {filepath} from {url}")
                    summary = get_gemini_summary(url)
                    if summary:
                        # Remove old description if it exists
                        new_front_matter_str = re.sub(r'\ndescription: ".*?"', '', new_front_matter_str)
                        # Add new summary
                        new_front_matter_str += f'\ndescription: "{summary}"'
                        made_changes = True

            # Add image_alt if it doesn't exist
            if 'image_alt:' not in front_matter_str:
                title_match = re.search(r'title:\s*"(.*?)"', front_matter_str)
                if title_match:
                    title = title_match.group(1)
                    new_front_matter_str += f'\nimage_alt: "{title} - Generative AI News"'
                    made_changes = True

            # Write back to file if changed
            if made_changes:
                new_content = f'---\n{new_front_matter_str}\n---\n{body}'
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"Updated front matter for {filepath}")

        except Exception as e:
            print(f"Error processing {filepath}: {e}")

if __name__ == '__main__':
    posts_directory = 'content/posts'
    add_descriptions_and_alt_text_to_posts(posts_directory)
