
import os
import re
import subprocess
from pathlib import Path

def add_summaries_to_posts(posts_dir):
    """
    Adds a summary to the front matter of Markdown posts if it's missing.
    The summary is generated by a sub-agent.
    """
    for filepath in Path(posts_dir).rglob('*.md'):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()

            # Simple front matter and body extraction
            parts = content.split('---', 2)
            if len(parts) < 3:
                print(f"Skipping {filepath}: Not a valid front matter format.")
                continue

            front_matter_str = parts[1]
            body = parts[2].strip()

            # Check if summary exists
            if 'summary:' in front_matter_str:
                continue

            # Get the link from the body
            link_match = re.search(r'\[Read the full article here\]\((.*?)\)', body)
            if not link_match:
                print(f"Skipping {filepath}: No link found.")
                continue
            
            link = link_match.group(1)

            # Spawn a sub-agent to summarize the article
            task = f"Please summarize the article at this URL: {link}"
            summary_process = subprocess.run(
                ['./summarize.sh', link],
                capture_output=True,
                text=True,
                check=True
            )
            summary = summary_process.stdout.strip()


            # Add summary to the post
            new_body = f"{summary}\n\n{body}"
            
            # Write back to file
            new_content = f'---\n{front_matter_str.strip()}\n---\n{new_body}'
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            
            print(f"Added summary to {filepath}")

        except Exception as e:
            print(f"Error processing {filepath}: {e}")

if __name__ == '__main__':
    posts_directory = 'content/posts'
    add_summaries_to_posts(posts_directory)
