baseURL = 'https://TheThinker0314.github.io/GenAI-news-site/'
languageCode = 'en-us'
title = 'GenAI News Site'
theme = 'ananke'
description = 'Your daily source for the latest news and trends in Generative AI.'
